package sicfun.holdem.io
import sicfun.holdem.types.*
import sicfun.holdem.engine.*
import sicfun.holdem.cli.*
import sicfun.holdem.equity.*

import sicfun.core.{Card, DiscreteDistribution}

import java.net.URLDecoder
import java.nio.charset.StandardCharsets
import java.nio.file.Path
import scala.jdk.CollectionConverters.*

/**
 * TSV reader for DDRE (Data-Driven Range Estimation) self-play training datasets.
 *
 * These datasets are generated by [[sicfun.holdem.runtime.PlayingHall]] (the self-play
 * simulation engine), which runs thousands of poker hands between bot players and records
 * every villain decision point along with the ground-truth hole cards and Bayesian posteriors.
 * The resulting dataset is used to train the DDRE neural network to approximate the
 * analytical Bayesian range updater at much lower inference cost.
 *
 * Each row in the TSV contains:
 *   - The game state at the decision point (street, board, pot, stacks, bet history)
 *   - Both players' actual hole cards (ground truth)
 *   - The sequence of villain observations leading to this point
 *   - The Bayesian prior and posterior distributions over the villain's possible hole cards
 *   - The log-evidence from the Bayesian update (for NLL-based training loss)
 *
 * Key design decisions:
 *   - '''Read-only''': This object only reads datasets; writing is handled by the PlayingHall
 *     exporter to keep the I/O contract unidirectional.
 *   - '''Sparse distribution encoding''': Prior and posterior distributions are stored as
 *     pipe-delimited `holeCardId:probability` pairs to avoid serializing ~1326 entries when
 *     most have negligible probability.
 *   - '''URL-encoded nested structures''': Bet history within observations uses URL encoding
 *     to avoid conflicts with the pipe and comma delimiters used at the observation level.
 *
 * Reads DDRE self-play datasets exported by `TexasHoldemPlayingHall`. */
object HoldemDdreDatasetIO:
  /** A single DDRE training sample representing one villain decision point.
   *
   * @param hand              hand number within the self-play session
   * @param tableId           table identifier for multi-table sessions
   * @param decisionIndex     ordinal position of this decision within the hand
   * @param state             game state from the hero's perspective at the decision point
   * @param villainPosition   table position of the villain
   * @param villainStackBefore villain's stack size before the action
   * @param observations      sequence of villain actions observed so far (for Bayesian updates)
   * @param heroHole          hero's actual hole cards (ground truth)
   * @param villainHole       villain's actual hole cards (ground truth, used as training label)
   * @param bayesLogEvidence  log-evidence from the analytical Bayesian update (training signal for NLL loss)
   * @param prior             prior distribution over villain's hole cards before this observation
   * @param bayesPosterior    posterior distribution from the analytical Bayesian updater (training target)
   */
  final case class Sample(
      hand: Int,
      tableId: Int,
      decisionIndex: Int,
      state: GameState,
      villainPosition: Position,
      villainStackBefore: Double,
      observations: Vector[VillainObservation],
      heroHole: HoleCards,
      villainHole: HoleCards,
      bayesLogEvidence: Double,
      prior: DiscreteDistribution[HoleCards],
      bayesPosterior: DiscreteDistribution[HoleCards]
  )

  private val ExpectedColumns = Vector(
    "hand",
    "tableId",
    "decisionIndex",
    "street",
    "board",
    "potBefore",
    "toCall",
    "heroPosition",
    "villainPosition",
    "heroStackBefore",
    "villainStackBefore",
    "betHistory",
    "villainObservations",
    "heroHole",
    "villainHole",
    "bayesLogEvidence",
    "priorSparse",
    "bayesPosteriorSparse"
  )

  /** Reads and parses a DDRE self-play dataset from a TSV file.
   *
   * Validates the header row against the expected 18-column schema,
   * then parses each non-empty data row into a [[Sample]].
   *
   * @param path the TSV file path
   * @return all parsed samples in file order
   * @throws IllegalArgumentException if the file is missing, empty, or has a header mismatch
   */
  def read(path: Path): Vector[Sample] =
    require(java.nio.file.Files.isRegularFile(path), s"DDRE dataset file not found: $path")
    val lines = java.nio.file.Files.readAllLines(path, StandardCharsets.UTF_8).asScala.toVector
    require(lines.nonEmpty, s"DDRE dataset file is empty: $path")
    val header = lines.head.split("\t", -1).toVector
    require(header == ExpectedColumns, s"DDRE dataset header mismatch: ${header.mkString(",")}")

    lines.drop(1).zipWithIndex.collect {
      case (line, index) if line.trim.nonEmpty =>
        parseRow(path, rowNumber = index + 2, line)
    }

  /** Parses a single TSV row into a [[Sample]], constructing the GameState,
   * observations, hole cards, and sparse distributions from their serialized forms.
   */
  private def parseRow(path: Path, rowNumber: Int, line: String): Sample =
    val cols = line.split("\t", -1).toVector
    require(cols.length == ExpectedColumns.length, s"$path:$rowNumber expected ${ExpectedColumns.length} columns, got ${cols.length}")

    def col(i: Int): String = cols(i).trim

    val state = GameState(
      street = parseStreet(col(3), path, rowNumber),
      board = parseBoard(col(4), path, rowNumber),
      pot = parseDouble(col(5), path, rowNumber, "potBefore"),
      toCall = parseDouble(col(6), path, rowNumber, "toCall"),
      position = parsePosition(col(7), path, rowNumber, "heroPosition"),
      stackSize = parseDouble(col(9), path, rowNumber, "heroStackBefore"),
      betHistory = parseBetHistory(col(11), path, rowNumber)
    )

    Sample(
      hand = parseInt(col(0), path, rowNumber, "hand"),
      tableId = parseInt(col(1), path, rowNumber, "tableId"),
      decisionIndex = parseInt(col(2), path, rowNumber, "decisionIndex"),
      state = state,
      villainPosition = parsePosition(col(8), path, rowNumber, "villainPosition"),
      villainStackBefore = parseDouble(col(10), path, rowNumber, "villainStackBefore"),
      observations = parseObservations(col(12), path, rowNumber),
      heroHole = CliHelpers.parseHoleCards(col(13)),
      villainHole = CliHelpers.parseHoleCards(col(14)),
      bayesLogEvidence = parseDouble(col(15), path, rowNumber, "bayesLogEvidence"),
      prior = parseSparsePosterior(col(16), path, rowNumber, "priorSparse"),
      bayesPosterior = parseSparsePosterior(col(17), path, rowNumber, "bayesPosteriorSparse")
    )

  /** Parses a sparse probability distribution from pipe-delimited "holeCardId:probability" pairs.
   *
   * Each entry maps a canonical hole-card ID (from [[HoleCardsIndex]]) to its probability.
   * The resulting distribution is normalized to sum to 1.0.
   */
  private def parseSparsePosterior(
      raw: String,
      path: Path,
      rowNumber: Int,
      field: String
  ): DiscreteDistribution[HoleCards] =
    if raw == "-" || raw.isEmpty then
      throw new IllegalArgumentException(s"$path:$rowNumber $field must be non-empty")
    val weights = raw.split("\\|").toVector.map { part =>
      val pieces = part.split(":", 2)
      if pieces.length != 2 then
        throw new IllegalArgumentException(s"$path:$rowNumber invalid $field entry: $part")
      val id = parseInt(pieces(0), path, rowNumber, s"$field.id")
      val probability = parseDouble(pieces(1), path, rowNumber, s"$field.probability")
      HoleCardsIndex.byId(id) -> probability
    }.toMap
    DiscreteDistribution(weights).normalized

  /** Parses the villain observation sequence from a pipe-delimited, key=value encoded string.
   *
   * Each observation is a comma-separated set of key=value fields:
   *   st (street), a (action), pot, call, pos (position), board, stack, history
   * The history field is URL-encoded to avoid delimiter conflicts.
   */
  private def parseObservations(raw: String, path: Path, rowNumber: Int): Vector[VillainObservation] =
    if raw == "-" || raw.isEmpty then Vector.empty
    else
      raw.split("\\|").toVector.map { item =>
        val fields = item.split(",").toVector.map { part =>
          val pieces = part.split("=", 2)
          if pieces.length != 2 then
            throw new IllegalArgumentException(s"$path:$rowNumber invalid observation token: $part")
          pieces(0).trim -> pieces(1).trim
        }.toMap

        val street = parseStreet(requiredField(fields, "st", path, rowNumber), path, rowNumber)
        val action = parseAction(requiredField(fields, "a", path, rowNumber), path, rowNumber)
        val pot = parseDouble(requiredField(fields, "pot", path, rowNumber), path, rowNumber, "pot")
        val toCall = parseDouble(requiredField(fields, "call", path, rowNumber), path, rowNumber, "call")
        val position = parsePosition(requiredField(fields, "pos", path, rowNumber), path, rowNumber, "pos")
        val board = parseBoard(requiredField(fields, "board", path, rowNumber), path, rowNumber)
        val stackSize = fields.get("stack").flatMap(_.toDoubleOption).getOrElse(0.0)
        val betHistory = fields
          .get("history")
          .map(raw => URLDecoder.decode(raw, StandardCharsets.UTF_8))
          .map(parseBetHistory(_, path, rowNumber))
          .getOrElse(Vector.empty)
        VillainObservation(
          action = action,
          state = GameState(
            street = street,
            board = board,
            pot = pot,
            toCall = toCall,
            position = position,
            stackSize = stackSize,
            betHistory = betHistory
          )
        )
      }

  /** Parses bet history from pipe-delimited entries with key=value fields (p=player, a=action). */
  private def parseBetHistory(raw: String, path: Path, rowNumber: Int): Vector[BetAction] =
    if raw == "-" || raw.isEmpty then Vector.empty
    else
      raw.split("\\|").toVector.map { item =>
        val fields = item.split(",").toVector.map { part =>
          val pieces = part.split("=", 2)
          if pieces.length != 2 then
            throw new IllegalArgumentException(s"$path:$rowNumber invalid betHistory token: $part")
          pieces(0).trim -> pieces(1).trim
        }.toMap
        BetAction(
          player = parseInt(requiredField(fields, "p", path, rowNumber), path, rowNumber, "betHistory.player"),
          action = parseAction(requiredField(fields, "a", path, rowNumber), path, rowNumber)
        )
      }

  private def parseAction(raw: String, path: Path, rowNumber: Int): PokerAction =
    raw.trim.toLowerCase match
      case "fold" => PokerAction.Fold
      case "check" => PokerAction.Check
      case "call" => PokerAction.Call
      case value if value.startsWith("raise:") =>
        val amount = value.drop(6).toDoubleOption.getOrElse(
          throw new IllegalArgumentException(s"$path:$rowNumber invalid raise token: $raw")
        )
        PokerAction.Raise(amount)
      case _ =>
        throw new IllegalArgumentException(s"$path:$rowNumber invalid action token: $raw")

  private def parseBoard(raw: String, path: Path, rowNumber: Int): Board =
    if raw == "-" || raw.isEmpty then Board.empty
    else
      val cards = raw.split("\\s+").toVector.map { token =>
        Card.parse(token).getOrElse(
          throw new IllegalArgumentException(s"$path:$rowNumber invalid card token: $token")
        )
      }
      Board.from(cards)

  private def parseStreet(raw: String, path: Path, rowNumber: Int): Street =
    Street.values.find(_.toString == raw).getOrElse(
      throw new IllegalArgumentException(s"$path:$rowNumber invalid street: $raw")
    )

  private def parsePosition(raw: String, path: Path, rowNumber: Int, field: String): Position =
    Position.values.find(_.toString == raw).getOrElse(
      throw new IllegalArgumentException(s"$path:$rowNumber invalid $field: $raw")
    )

  private def parseInt(raw: String, path: Path, rowNumber: Int, field: String): Int =
    raw.toIntOption.getOrElse(
      throw new IllegalArgumentException(s"$path:$rowNumber invalid $field: $raw")
    )

  private def parseDouble(raw: String, path: Path, rowNumber: Int, field: String): Double =
    raw.toDoubleOption.getOrElse(
      throw new IllegalArgumentException(s"$path:$rowNumber invalid $field: $raw")
    )

  /** Extracts a required field from a key=value map, throwing if the key is absent. */
  private def requiredField(
      fields: Map[String, String],
      key: String,
      path: Path,
      rowNumber: Int
  ): String =
    fields.getOrElse(
      key,
      throw new IllegalArgumentException(s"$path:$rowNumber missing field '$key'")
    )
